name: Validate Sigma Rules
description: "Validate Sigma rules using the JSON schema"
branding:
  icon: check-circle
  color: green
inputs:
  path:
    description: "Path to the Sigma rules"
    required: false
    default: "./"
  schemaPath:
    description: "Path to the JSON schema"
    required: false
    default: "https://raw.githubusercontent.com/SigmaHQ/sigma-specification/main/sigma-schema.json"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v5
    - name: Install dependencies
      shell: bash
      run: pip install check-jsonschema
    - name: Validate Sigma rules
      shell: bash
      run: ${{ github.action_path }}/validate.sh
      env:
        SIGMA_RULES_PATH: ${{ inputs.path }}
        SIGMA_SCHEMA_PATH: ${{ inputs.schemaPath }}
